### ISSUE TITLE
Tests

### ISSUE THREAD

**Issue by kangarang** [kangarang/tcr-ui#33]
https://medium.com/javascript-inside/some-thoughts-on-testing-react-redux-applications-8571fbc1b78f

https://medium.com/javascript-scene/mocking-is-a-code-smell-944a70c90a6a

https://medium.com/javascript-scene/tdd-the-rite-way-53c9b46f45e3

call setup and teardown routines from individual tests, and contain all state to local test variables

minimize matchers: `toBe`, `toEqual`

### Todo
- [x] Add build / CI
- [x] Jest coverage
- [x] Fix npm build (ipfs-api)

**libs**
- [ ] [ipfs.js](https://github.com/kangarang/tcr-ui/blob/master/src/state/libs/ipfs.js)
- [x] [provider.js](https://github.com/kangarang/tcr-ui/blob/master/src/state/libs/provider.js)
- [x] [units.js](https://github.com/kangarang/tcr-ui/blob/master/src/state/libs/units.js)
- [x] [values.js](https://github.com/kangarang/tcr-ui/blob/master/src/state/libs/values.js)

**utils**
- [x] [_datetime.js](https://github.com/kangarang/tcr-ui/blob/master/src/state/utils/_datetime.js)
- [ ] [_file.js](https://github.com/kangarang/tcr-ui/blob/master/src/state/utils/_file.js)

**ducks**
- [ ] [home](https://github.com/kangarang/tcr-ui/blob/master/src/state/ducks/home)
- [ ] [transactions](https://github.com/kangarang/tcr-ui/blob/master/src/state/ducks/transactions)
- [ ] [listings](https://github.com/kangarang/tcr-ui/blob/master/src/state/ducks/listings)
- [ ] [logs](https://github.com/kangarang/rut/blob/master/src/redux/modules/logs)
- [ ] [ethereumProvider](https://github.com/kangarang/tcr-ui/tree/master/src/state/ducks/ethereumProvider)

**Comment by kangarang** [comment]
https://facebook.github.io/jest/docs/en/tutorial-react.html

https://facebook.github.io/jest/docs/en/using-matchers.html

https://medium.com/javascript-inside/some-thoughts-on-testing-react-redux-applications-8571fbc1b78f

**Comment by kangarang** [comment]
`utils/_units`
0377fc6ec4fae53fc1a515ad388a5900f434b1ac

**Comment by kangarang** [comment]
implement test env deployment pipeline
